import { existsSync, readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { repoRoot, readJsonSafe } from "../util.mjs";

const CONTRACTS = [
  "docs/vault/02_Contracts/API_Contracts.md",
  "docs/vault/02_Contracts/Navigation_Contract.md",
  "docs/vault/02_Contracts/SDUI_Schema.md",
  "docs/vault/02_Contracts/Ogu_Memory_Contract.md",
  "docs/vault/02_Contracts/Design_System_Contract.md",
  "docs/vault/02_Contracts/Artifact_Contract.md",
  "docs/vault/02_Contracts/Preview_Contract.md",
  "docs/vault/02_Contracts/Deploy_Packs.md",
];

const CONTRACT_SCHEMAS = [
  "docs/vault/02_Contracts/api.contract.json",
  "docs/vault/02_Contracts/navigation.contract.json",
  "docs/vault/02_Contracts/design.tokens.json",
];

const DEFAULT_BUDGET = 80000;

export async function context(overrideArgs) {
  const args = overrideArgs || process.argv.slice(3);
  const feature = parseFlag(args, "--feature");
  const issue = parseFlag(args, "--issue");
  const budget = parseInt(parseFlag(args, "--budget")) || DEFAULT_BUDGET;
  const root = repoRoot();

  // Build sections with priorities (P1 = highest, P4 = lowest)
  const sectionDefs = [
    { priority: 1, name: "Invariants", builder: () => buildSection("Section 1 — Invariants", root, ["docs/vault/01_Architecture/Invariants.md"]) },
    { priority: 1, name: "Feature Spec", builder: () => buildFeatureSection(root, feature, issue), condition: !!feature },
    { priority: 1, name: "Feature Contracts", builder: () => buildFeatureContracts(root, feature), condition: !!feature },
    { priority: 2, name: "Memory", builder: () => buildSection("Section 6 — Memory", root, [".ogu/MEMORY.md"]) },
    { priority: 2, name: "Repo Map", builder: () => buildSection("Section 3 — Repo Map", root, ["docs/vault/01_Architecture/Repo_Map.md"]) },
    { priority: 2, name: "Design Theme", builder: () => buildThemeSection(root) },
    { priority: 2, name: "Project Profile", builder: () => buildProfileSection(root) },
    { priority: 3, name: "Patterns", builder: () => buildSection("Section 4 — Patterns", root, ["docs/vault/01_Architecture/Patterns.md"]) },
    { priority: 3, name: "Contracts", builder: () => buildSection("Section 2 — Contracts", root, feature ? getUnusedContracts(root, feature) : [...CONTRACTS, ...CONTRACT_SCHEMAS]) },
    { priority: 4, name: "Recent Logs", builder: () => buildRecentLogs(root) },
  ];

  // Build all sections
  const built = [];
  for (const def of sectionDefs) {
    if (def.condition === false) continue;
    const content = def.builder();
    if (!content || content.trim().length === 0) continue;
    built.push({ ...def, content, tokens: estimateTokens(content) });
  }

  // Budget enforcement — truncate from P4 up
  let totalTokens = built.reduce((sum, s) => sum + s.tokens, 0);
  const truncated = [];

  if (totalTokens > budget) {
    for (const p of [4, 3, 2]) {
      if (totalTokens <= budget) break;
      const sectionsAtP = built.filter((s) => s.priority === p);
      for (const s of sectionsAtP) {
        if (totalTokens <= budget) break;
        const saved = s.tokens;
        s.content = `<!-- Section truncated: ${s.name} (was ~${saved} tokens, budget exceeded) -->\n`;
        s.tokens = estimateTokens(s.content);
        totalTokens -= saved - s.tokens;
        truncated.push(s.name);
      }
    }
  }

  // Assemble
  const header = `<!-- Generated by \`ogu context\`. Do not edit manually. -->\n<!-- Built: ${new Date().toISOString()} -->\n\n`;
  const body = built.map((s) => s.content).join("\n\n---\n\n");
  const budgetFooter = `\n\n<!-- Context budget: ${totalTokens}/${budget} tokens. ${built.length - truncated.length} full, ${truncated.length} truncated -->\n`;
  const output = header + body + budgetFooter;

  const contextPath = join(root, ".ogu/CONTEXT.md");
  writeFileSync(contextPath, output, "utf-8");

  // Update STATE.json
  const statePath = join(root, ".ogu/STATE.json");
  if (existsSync(statePath)) {
    try {
      const state = JSON.parse(readFileSync(statePath, "utf-8"));
      state.last_context_build = new Date().toISOString();
      writeFileSync(statePath, JSON.stringify(state, null, 2) + "\n", "utf-8");
    } catch { /* leave as-is */ }
  }

  console.log(`  assembled  .ogu/CONTEXT.md (~${totalTokens} tokens, budget ${budget})`);
  if (feature) console.log(`  feature    ${feature}`);
  if (issue) console.log(`  issue      ${issue}`);
  if (truncated.length > 0) console.log(`  truncated  ${truncated.join(", ")}`);
  return 0;
}

// ---------------------------------------------------------------------------
// Token estimation
// ---------------------------------------------------------------------------

function estimateTokens(text) {
  return Math.ceil(text.length / 4);
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

function buildSection(title, root, paths) {
  let md = `# ${title}\n`;

  for (const relPath of paths) {
    const full = join(root, relPath);
    md += `\n## ${relPath}\n\n`;
    if (existsSync(full)) {
      md += readFileSync(full, "utf-8").trim() + "\n";
    } else {
      md += `> MISSING: ${relPath}\n`;
    }
  }

  return md;
}

function buildFeatureSection(root, feature, issue) {
  let md = "# Section 5 — Feature Spec\n";

  if (!feature) {
    md += "\nNo feature specified.\n";
    return md;
  }

  if (issue) {
    md += `\n## Issue\n\n${issue}\n`;
  }

  const featureFiles = [
    `docs/vault/04_Features/${feature}/PRD.md`,
    `docs/vault/04_Features/${feature}/Spec.md`,
    `docs/vault/04_Features/${feature}/QA.md`,
    `docs/vault/04_Features/${feature}/Plan.json`,
  ];

  for (const relPath of featureFiles) {
    const full = join(root, relPath);
    md += `\n## ${relPath}\n\n`;
    if (existsSync(full)) {
      md += readFileSync(full, "utf-8").trim() + "\n";
    } else {
      md += `> MISSING: ${relPath}\n`;
    }
  }

  return md;
}

function buildFeatureContracts(root, feature) {
  if (!feature) return "";

  // Scan Spec.md for contract references
  const specPath = join(root, `docs/vault/04_Features/${feature}/Spec.md`);
  if (!existsSync(specPath)) return "";

  const spec = readFileSync(specPath, "utf-8").toLowerCase();
  const relevant = [];

  // Match contracts mentioned in spec
  for (const c of [...CONTRACTS, ...CONTRACT_SCHEMAS]) {
    const name = c.split("/").pop().replace(/\.(md|json)$/, "").toLowerCase();
    if (spec.includes(name) || spec.includes(name.replace(/_/g, " "))) {
      relevant.push(c);
    }
  }

  // Always include API and Navigation contracts if spec mentions API/routes
  if (spec.includes("api") || spec.includes("endpoint")) {
    if (!relevant.includes(CONTRACTS[0])) relevant.push(CONTRACTS[0]);
    if (!relevant.includes(CONTRACT_SCHEMAS[0])) relevant.push(CONTRACT_SCHEMAS[0]);
  }
  if (spec.includes("route") || spec.includes("navigation") || spec.includes("page")) {
    if (!relevant.includes(CONTRACTS[1])) relevant.push(CONTRACTS[1]);
    if (!relevant.includes(CONTRACT_SCHEMAS[1])) relevant.push(CONTRACT_SCHEMAS[1]);
  }
  if (spec.includes("design") || spec.includes("token") || spec.includes("theme") || spec.includes("ui")) {
    if (!relevant.includes(CONTRACTS[4])) relevant.push(CONTRACTS[4]);
    if (!relevant.includes(CONTRACT_SCHEMAS[2])) relevant.push(CONTRACT_SCHEMAS[2]);
  }

  if (relevant.length === 0) return "";
  return buildSection("Section 2a — Feature-Relevant Contracts", root, relevant);
}

function getUnusedContracts(root, feature) {
  // When feature contracts are included at P1, the general contracts section
  // includes only the remaining ones at P3
  const specPath = join(root, `docs/vault/04_Features/${feature}/Spec.md`);
  if (!existsSync(specPath)) return [...CONTRACTS, ...CONTRACT_SCHEMAS];

  const spec = readFileSync(specPath, "utf-8").toLowerCase();
  const all = [...CONTRACTS, ...CONTRACT_SCHEMAS];

  return all.filter((c) => {
    const name = c.split("/").pop().replace(/\.(md|json)$/, "").toLowerCase();
    return !spec.includes(name) && !spec.includes(name.replace(/_/g, " "));
  });
}

function buildThemeSection(root) {
  const themePath = join(root, ".ogu/THEME.json");
  const theme = readJsonSafe(themePath);
  if (!theme) return "";

  let md = "# Section 2.5 — Design Theme\n\n";
  md += `Mood: ${theme.mood}\n`;
  if (theme.description) md += `Description: ${theme.description}\n`;
  if (theme.generated_tokens?.colors) {
    const c = theme.generated_tokens.colors;
    md += `Key colors: primary=${c.primary || "—"}, background=${c.background || "—"}, secondary=${c.secondary || "—"}\n`;
  }
  if (theme.generated_tokens?.typography?.font_body) {
    md += `Typography: ${theme.generated_tokens.typography.font_body}\n`;
  }
  if (theme.constraints) {
    const constraints = Object.entries(theme.constraints)
      .map(([k, v]) => `${k}=${v}`)
      .join(", ");
    md += `Constraints: ${constraints}\n`;
  }

  return md;
}

function buildProfileSection(root) {
  const profilePath = join(root, ".ogu/PROFILE.json");
  const profile = readJsonSafe(profilePath);
  if (!profile) return "";

  let md = "# Section 2.6 — Project Profile\n\n";
  md += `Platform: ${profile.platform}\n`;
  md += `Services: ${(profile.services || []).join(", ") || "none"}\n`;

  const needs = Object.entries(profile)
    .filter(([k, v]) => k.startsWith("needs_") && v === true)
    .map(([k]) => k.replace("needs_", ""));

  if (needs.length > 0) {
    md += `Infrastructure needs: ${needs.join(", ")}\n`;
  }

  md += "\nUse this profile to inform architecture decisions, build commands, and preview configuration.\n";

  return md;
}

function buildRecentLogs(root) {
  let md = "# Section 7 — Recent Logs\n";

  const memDir = join(root, ".ogu/memory");
  if (!existsSync(memDir)) {
    md += "\nNo logs directory found.\n";
    return md;
  }

  const logFiles = readdirSync(memDir)
    .filter((f) => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
    .sort()
    .reverse()
    .slice(0, 2);

  if (logFiles.length === 0) {
    md += "\nNo daily logs found.\n";
    return md;
  }

  for (const file of logFiles) {
    const full = join(memDir, file);
    md += `\n## .ogu/memory/${file}\n\n`;
    md += readFileSync(full, "utf-8").trim() + "\n";
  }

  return md;
}

// ---------------------------------------------------------------------------

function parseFlag(args, flag) {
  const idx = args.indexOf(flag);
  if (idx === -1 || idx + 1 >= args.length) return null;
  return args[idx + 1];
}
